### ISSUE TITLE
IVector complete toolchain missing

### ISSUE THREAD

**Issue by khoury** [bioidiap/facereclib#7]
The complete toolchain of IVector including Whitening, L-Norm, LDA, WCCN, and PLDA, and score computation is missing.

**Comment by tiagofrepereira2012** [comment]
Hey,

Do we have this feature with the bob.bio.* ?
I think we can close this one, right?

I will close it, but if I'm wrong reopen it.

Cheers

**Comment by khoury** [comment]
Right, all good now with bob.bio.gmm
